branch-defaults:
  main:
    environment: KinoServer-env
    group_suffix: null
deploy:
  artifact: target/kino-server-0.0.1-SNAPSHOT.jar
environment-defaults:
  KinoServer-env:
    branch: main
    repository: kino-server
global:
  application_name: Kino Server
  branch: main
  default_ec2_keyname: null
  default_platform: Corretto 21 running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: kino-server
  sc: git
  workspace_type: Application
